### ISSUE TITLE
DropDatabaseInUse

### ISSUE THREAD

**Issue by ianhenrygim** [ivawzh/pg-god#1]
hi, 
I want to drop database, but it always make an error.

Here is my code.

```
// close database connection
await databaseConnectionManager
    .get(databaseName)
    .close()
    .catch((error) => console.log(error))

// drop database
await dropDatabase( { databaseName },
        {
            user: process.env.TYPEORM_USERNAME,
            password: process.env.TYPEORM_PASSWORD,
            host: process.env.TYPEORM_HOST,
            port: Number(process.env.TYPEORM_PORT),
            database: databaseName,
        }
    ).catch((error) => console.error(error));
```

And the error message is, 
```
PgGodError {
  name: 'PDG_ERR::DropDatabaseInUse',
  message: 'Cannot delete a database that is being accessed by other users.',
  code: '55006',
  ...
}
```

I don't know how can I close all connections programmatically... Do you know any suggestion?

**Comment by ivawzh** [comment]
Hi @ianhenrygim, thanks for bringing up a good common problem.

I have released a new version `1.0.6` that kills all active connections by default when drop database.

You may opt-out with API opt `dropConnections: false` or command flag `--no-dropConnections`.
