### ISSUE TITLE
Feature Request : connection url string

### ISSUE THREAD

**Issue by cyrilchapon** [ivawzh/pg-god#2]
Connection URL is the defacto standard in many environments.

MikroORM covers it (using `url` instead of everything else); it would be awesome if this package covered it to.

**Comment by cyrilchapon** [comment]
Eg: `dotenv -- pg-god --url=$DATABASE_URL`

It should parse everything, including db name :D

**Comment by ivawzh** [comment]
Hey @cyrilchapon , I have made an update with URL supports. Hope you will like it.

See details at https://github.com/ivawzh/pg-god/releases/tag/v1.0.9
