### ISSUE TITLE
Yarn add throws "JavaScript heap out of memory" error when running "yarn add pg-god"

### ISSUE THREAD

**Issue by elliotaplant** [ivawzh/pg-god#8]
I'm moving my repo from npm to yarn and I found that pg-god was causing yarn to run out of memory.

I'm using a `MacBook Air (M1, 2020)`, `node --version : v16.13.0`, `yarn --version : 1.22.17`

I suspect this is an issue with one of pg-god's dependencies, but I thought I would bring the issue here because it might be an issue for other people too

**Comment by EmanoelFaria** [comment]
pg-god uses a dependency called colors, 3 days ago the responsible dev submitted a commit that creates a infinity loop on it purposefully https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6#comments

**Comment by ivawzh** [comment]
Thanks for reporting this issue. 

And thank @EmanoelFaria for the good story about its cause.

I call this life 👇 
![image](https://user-images.githubusercontent.com/4622799/183279891-ae549fdb-1415-447e-9abf-02e21bae2d39.png)
